<?php

use App\Http\Controllers\Api\V1\HealthCheckController;
use App\Http\Controllers\Api\V1\AuthController;
use App\Http\Controllers\Api\V1\CategoryController;
use App\Http\Controllers\Api\V1\TransactionController;
use App\Http\Controllers\Api\V1\ReportController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| API Routes — v1
|--------------------------------------------------------------------------
|
| Flow  : Route → Controller → Service → Repository ↔ Interface → Model
| Auth  : Laravel Sanctum (Bearer token)
| Docs  : /docs  (auto-generated by dedoc/scramble)
| Health: /api/health (no auth)
|
*/

Route::get('health', HealthCheckController::class);

Route::prefix('v1')->group(function () {

    // ── Public — Auth ──────────────────────────────────────────────────────────
    Route::prefix('auth')->middleware('throttle:auth')->group(function () {
        Route::post('register', [AuthController::class, 'register']);
        Route::post('login',    [AuthController::class, 'login']);
    });

    // ── Protected ──────────────────────────────────────────────────────────────
    Route::middleware(['auth:sanctum', 'throttle:api', 'not.banned'])->group(function () {

        // Auth (self)
        Route::prefix('auth')->group(function () {
            Route::get('me',      [AuthController::class, 'me']);
            Route::put('me',      [AuthController::class, 'updateProfile']);
            Route::post('logout', [AuthController::class, 'logout']);
        });

        Route::get('categories/search', [CategoryController::class, 'search']);
        Route::apiResource('categories', CategoryController::class);

        Route::apiResource('transactions', TransactionController::class);
        Route::post('transactions/{transaction}/restore', [TransactionController::class, 'restore']);

        Route::prefix('reports')->group(function () {
            Route::get('summary',              [ReportController::class, 'summary']);
            Route::get('profit-loss',          [ReportController::class, 'profitLoss']);
            Route::get('cash-flow',            [ReportController::class, 'cashFlow']);
            Route::get('by-category',          [ReportController::class, 'byCategory']);
            Route::get('trend',                [ReportController::class, 'trend']);
            Route::get('export',               [ReportController::class, 'export'])->middleware('throttle:export');
            Route::get('export/status/{jobId}',[ReportController::class, 'exportStatus']);
        });
    });
});
