<?php

use App\Http\Controllers\Api\V1\HealthCheckController;
use App\Http\Controllers\Api\V1\AuthController;
use App\Http\Controllers\Api\V1\CategoryController;
use App\Http\Controllers\Api\V1\TransactionController;
use App\Http\Controllers\Api\V1\ReportController;
use App\Http\Controllers\Api\V1\ActivityLogController;
use App\Http\Controllers\Api\V1\AiInsightController;
use Illuminate\Support\Facades\Route;
use OpenAI\Laravel\Facades\OpenAI;

/*
|--------------------------------------------------------------------------
| API Routes — v1
|--------------------------------------------------------------------------
|
| Flow  : Route > Controller > Service > Repository <> Interface > Model
| Auth  : Laravel Sanctum (Bearer token)
| Docs  : /docs  (auto-generated by dedoc/scramble)
| AI    : Open Router x OpenAi (by openai-php/laravel)
| Health: /api/health (no auth)
|
*/

Route::get('health', HealthCheckController::class);

Route::prefix('v1')->group(function () {

    Route::prefix('auth')->middleware('throttle:auth')->group(function () {
        Route::post('register', [AuthController::class, 'register']);
        Route::post('login',    [AuthController::class, 'login']);
    });

    Route::middleware(['auth:sanctum', 'throttle:api', 'not.banned'])->group(function () {

        Route::prefix('auth')->group(function () {
            Route::get('me',      [AuthController::class, 'me']);
            Route::put('me',      [AuthController::class, 'updateProfile']);
            Route::post('logout', [AuthController::class, 'logout']);
        });

        Route::get('categories/search', [CategoryController::class, 'search']);
        Route::apiResource('categories', CategoryController::class);

        Route::apiResource('transactions', TransactionController::class);
        Route::post('transactions/{transaction}/restore', [TransactionController::class, 'restore']);

        Route::prefix('reports')->group(function () {
            Route::get('summary',              [ReportController::class, 'summary']);
            Route::get('profit-loss',          [ReportController::class, 'profitLoss']);
            Route::get('cash-flow',            [ReportController::class, 'cashFlow']);
            Route::get('by-category',          [ReportController::class, 'byCategory']);
            Route::get('trend',                [ReportController::class, 'trend']);
            Route::get('export',               [ReportController::class, 'export'])->middleware('throttle:export');
            Route::get('export/status/{jobId}',[ReportController::class, 'exportStatus']);
        });

        Route::prefix('activity')->group(function () {
            Route::get('/',       [ActivityLogController::class, 'index']);
            Route::get('summary', [ActivityLogController::class, 'summary']);
            Route::get('subject', [ActivityLogController::class, 'forSubject']);
        });

        Route::prefix('ai')->middleware('throttle:ai')->group(function () {
            Route::get('insights', [AiInsightController::class, 'insights']);
            Route::post('ask',     [AiInsightController::class, 'ask']);
        });
    });
});
