<?php

use App\Http\Controllers\Api\V1\HealthCheckController;
use App\Http\Controllers\Api\V1\AuthController;
use App\Http\Controllers\Api\V1\CategoryController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| API Routes — v1
|--------------------------------------------------------------------------
|
| Flow  : Route → Controller → Service → Repository ↔ Interface → Model
| Auth  : Laravel Sanctum (Bearer token)
| Docs  : /docs  (auto-generated by dedoc/scramble)
| Health: /api/health (no auth)
|
*/

Route::get('health', HealthCheckController::class);

Route::prefix('v1')->group(function () {

    // ── Public — Auth ──────────────────────────────────────────────────────────
    Route::prefix('auth')->middleware('throttle:auth')->group(function () {
        Route::post('register', [AuthController::class, 'register']);
        Route::post('login',    [AuthController::class, 'login']);
    });

    // ── Protected ──────────────────────────────────────────────────────────────
    Route::middleware(['auth:sanctum', 'throttle:api', 'not.banned'])->group(function () {

        // Auth (self)
        Route::prefix('auth')->group(function () {
            Route::get('me',      [AuthController::class, 'me']);
            Route::put('me',      [AuthController::class, 'updateProfile']);
            Route::post('logout', [AuthController::class, 'logout']);
        });

        Route::get('categories/search', [CategoryController::class, 'search']);
        Route::apiResource('categories', CategoryController::class);
    });
});
